from app.models import db, Business, Category, Feature, Food
from datetime import time

def seed_businesses():

    biz1 = Business(name='Bryce\'s Place', image_url='https://eatlocalapp.s3.amazonaws.com/anna-pelzer-IGfIGP5ONV0-unsplash.jpg', phone_num='5555555555', description='Family owned business, with affordable prices.', opening=time(10, 0), closing=time(21, 0), user_id=2)
    biz2 = Business(name='Burgers n Stuff', image_url='https://eatlocalapp.s3.amazonaws.com/anna-pelzer-IGfIGP5ONV0-unsplash.jpg', phone_num='5555555555', description='Family owned business, with affordable prices.', opening=time(10, 0), closing=time(21, 0), user_id=2)
    biz3 = Business(name='Salad Work', image_url='https://eatlocalapp.s3.amazonaws.com/anna-pelzer-IGfIGP5ONV0-unsplash.jpg', phone_num='5555555555', description='Family owned business, with affordable prices.', opening=time(10, 0), closing=time(21, 0), user_id=2)
    biz4 = Business(name='Bryce\'s Cafe', image_url='https://eatlocalapp.s3.amazonaws.com/anna-pelzer-IGfIGP5ONV0-unsplash.jpg', phone_num='5555555555', description='Family owned business, with affordable prices.', opening=time(10, 0), closing=time(21, 0), user_id=2)
    biz5 = Business(name='South Diner', image_url='https://eatlocalapp.s3.amazonaws.com/anna-pelzer-IGfIGP5ONV0-unsplash.jpg', phone_num='5555555555', description='Family owned business, with affordable prices.', opening=time(10, 0), closing=time(21, 0), user_id=2)
    biz6 = Business(name='B Corner Store', image_url='https://eatlocalapp.s3.amazonaws.com/anna-pelzer-IGfIGP5ONV0-unsplash.jpg', phone_num='5555555555', description='Family owned business, with affordable prices.', opening=time(10, 0), closing=time(21, 0), user_id=2)
    biz7 = Business(name='Halal Truck', image_url='https://eatlocalapp.s3.amazonaws.com/anna-pelzer-IGfIGP5ONV0-unsplash.jpg', phone_num='5555555555', description='Family owned business, with affordable prices.', opening=time(10, 0), closing=time(21, 0), user_id=2)
    biz8 = Business(name='Nagoya', image_url='https://eatlocalapp.s3.amazonaws.com/anna-pelzer-IGfIGP5ONV0-unsplash.jpg', phone_num='5555555555', description='Family owned business, with affordable prices.', opening=time(10, 0), closing=time(21, 0), user_id=2)
    biz9 = Business(name='Red River', image_url='https://eatlocalapp.s3.amazonaws.com/anna-pelzer-IGfIGP5ONV0-unsplash.jpg', phone_num='5555555555', description='Family owned business, with affordable prices.', opening=time(10, 0), closing=time(21, 0), user_id=2)
    biz10 = Business(name='Three Circles', image_url='https://eatlocalapp.s3.amazonaws.com/anna-pelzer-IGfIGP5ONV0-unsplash.jpg', phone_num='5555555555', description='Family owned business, with affordable prices.', opening=time(10, 0), closing=time(21, 0), user_id=2)
    biz11 = Business(name='Brother\'s Pizza', image_url='https://eatlocalapp.s3.amazonaws.com/anna-pelzer-IGfIGP5ONV0-unsplash.jpg', phone_num='5555555555', description='Family owned business, with affordable prices.', opening=time(10, 0), closing=time(21, 0), user_id=2)
    biz12 = Business(name='Cosmo\'s Deli', image_url='https://eatlocalapp.s3.amazonaws.com/anna-pelzer-IGfIGP5ONV0-unsplash.jpg', phone_num='5555555555', description='Family owned business, with affordable prices.', opening=time(10, 0), closing=time(21, 0), user_id=2)

    cat1 = Category(name='Breakfast')
    cat2 = Category(name='Lunch')
    cat3 = Category(name='Dinner')
    cat4 = Category(name='Bakery')
    cat5 = Category(name='Cafe')
    cat6 = Category(name='American')
    cat7 = Category(name='Asian')
    cat8 = Category(name='Chinese')
    cat9 = Category(name='Japanese')
    cat10 = Category(name='Vietnamese')
    cat11 = Category(name='Indian')
    cat12 = Category(name='Thai')
    cat13 = Category(name='Mexican')
    cat14 = Category(name='Venezualan')
    cat15 = Category(name='Mediterranean')
    cat16 = Category(name='Italian')

    feat1 = Feature(name='Takeout')
    feat2 = Feature(name='Delivery')
    feat3 = Feature(name='Outdoor Seating')

    food1 = Food(name='Breakfast Sandwich')
    food2 = Food(name='Bagel')
    food3 = Food(name='Muffin')
    food4 = Food(name='Croissant')
    food5 = Food(name='Yogurt')
    food6 = Food(name='"Nice" Cream')
    food7 = Food(name='Fruit Salad')
    food8 = Food(name='Garden Salad')
    food9 = Food(name='Caesar Salad')
    food10 = Food(name='Pastrami Sandwich')
    food11 = Food(name='Cheesesteak')
    food12 = Food(name='Caesar Salad')
    food13 = Food(name='Build Your Own Sandwich')
    food14 = Food(name='Pulled Pork')

    biz_list = [biz1, biz2, biz3, biz4, biz5, biz6, biz7, biz8, biz9, biz10, biz11, biz12]
    food_list = [food1, food2, food3, food4, food5, food6, food7, food8, food9, food10, food11, food12, food13, food14]

    for biz in biz_list:
        for food_item in food_list:
            biz.food.append(food_item)


    biz1.categories.append(cat1)
    biz1.categories.append(cat2)
    biz1.categories.append(cat3)
    biz1.categories.append(cat6)
    biz2.categories.append(cat2)
    biz2.categories.append(cat3)
    biz2.categories.append(cat6)
    biz3.categories.append(cat2)
    biz3.categories.append(cat3)
    biz4.categories.append(cat1)
    biz4.categories.append(cat2)
    biz4.categories.append(cat4)
    biz4.categories.append(cat5)
    biz5.categories.append(cat1)
    biz5.categories.append(cat2)
    biz5.categories.append(cat3)
    biz5.categories.append(cat6)
    biz6.categories.append(cat1)
    biz6.categories.append(cat2)
    biz6.categories.append(cat6)
    biz6.categories.append(cat10)
    biz7.categories.append(cat2)
    biz7.categories.append(cat3)
    biz7.categories.append(cat15)
    biz8.categories.append(cat2)
    biz8.categories.append(cat3)
    biz8.categories.append(cat7)
    biz8.categories.append(cat9)
    biz9.categories.append(cat2)
    biz9.categories.append(cat3)
    biz9.categories.append(cat7)
    biz9.categories.append(cat8)
    biz10.categories.append(cat2)
    biz10.categories.append(cat3)
    biz10.categories.append(cat7)
    biz10.categories.append(cat12)
    biz11.categories.append(cat1)
    biz11.categories.append(cat2)
    biz11.categories.append(cat3)
    biz11.categories.append(cat16)
    biz12.categories.append(cat1)
    biz12.categories.append(cat2)
    biz12.categories.append(cat6)

    biz1.features.append(feat1)
    biz1.features.append(feat2)
    biz2.features.append(feat1)
    biz2.features.append(feat2)
    biz3.features.append(feat1)
    biz4.features.append(feat3)
    biz5.features.append(feat1)
    biz6.features.append(feat2)
    biz7.features.append(feat1)
    biz8.features.append(feat3)

    db.session.add(biz1)
    db.session.add(biz2)
    db.session.add(biz3)
    db.session.add(biz4)
    db.session.add(biz5)
    db.session.add(biz6)
    db.session.add(biz7)
    db.session.add(biz8)
    db.session.add(biz9)
    db.session.add(biz10)
    db.session.add(biz11)
    db.session.add(biz12)

    db.session.commit()

def undo_businesses():
    db.session.execute('TRUNCATE businesses;')
    db.session.commit()
