from app.models import db, Food

def seed_food():

    food1 = Food(name='Breakfast Sandwich', business_id=1)
    food2 = Food(name='Bagel', business_id=1)
    food3 = Food(name='Muffin', business_id=1)
    food4 = Food(name='Croissant', business_id=1)
    food5 = Food(name='Yogurt', business_id=1)
    food6 = Food(name='"Nice" Cream', business_id=1)
    food7 = Food(name='Fruit Salad', business_id=1)
    food8 = Food(name='Garden Salad', business_id=1)
    food9 = Food(name='Caesar Salad', business_id=1)
    food10 = Food(name='Pastrami Sandwich', business_id=1)
    food11 = Food(name='Cheesesteak', business_id=1)
    food12 = Food(name='Caesar Salad', business_id=1)
    food13 = Food(name='Build Your Own Sandwich', business_id=1)
    food14 = Food(name='Pulled Pork', business_id=1)
    food15 = Food(name='Breakfast Sandwich', business_id=2)
    food16 = Food(name='Bagel', business_id=2)
    food17 = Food(name='Muffin', business_id=2)
    food18 = Food(name='Croissant', business_id=2)
    food19 = Food(name='Yogurt', business_id=2)
    food20 = Food(name='"Nice" Cream', business_id=2)
    food21 = Food(name='Fruit Salad', business_id=2)
    food22 = Food(name='Garden Salad', business_id=3)
    food23 = Food(name='Caesar Salad', business_id=3)
    food24 = Food(name='Pastrami Sandwich', business_id=3)
    food25 = Food(name='Cheesesteak', business_id=3)
    food26 = Food(name='Caesar Salad', business_id=3)
    food27 = Food(name='Build Your Own Sandwich', business_id=3)
    food28 = Food(name='Pulled Pork', business_id=3)
    food29 = Food(name='Breakfast Sandwich', business_id=3)
    food30 = Food(name='Bagel', business_id=3)
    food31 = Food(name='Muffin', business_id=3)
    food32 = Food(name='Croissant', business_id=3)
    food33 = Food(name='Yogurt', business_id=4)
    food34 = Food(name='"Nice" Cream', business_id=4)
    food35 = Food(name='Fruit Salad', business_id=4)
    food36 = Food(name='Garden Salad', business_id=4)
    food37 = Food(name='Caesar Salad', business_id=4)
    food38 = Food(name='Pastrami Sandwich', business_id=4)
    food39 = Food(name='Cheesesteak', business_id=5)
    food40 = Food(name='Caesar Salad', business_id=5)
    food41 = Food(name='Build Your Own Sandwich', business_id=5)
    food42 = Food(name='Pulled Pork', business_id=5)
    food43 = Food(name='Breakfast Sandwich', business_id=5)
    food44 = Food(name='Bagel', business_id=5)
    food45 = Food(name='Muffin', business_id=5)
    food46 = Food(name='Croissant', business_id=5)
    food47 = Food(name='Yogurt', business_id=5)
    food48 = Food(name='"Nice" Cream', business_id=5)
    food49 = Food(name='Fruit Salad', business_id=6)
    food50 = Food(name='Garden Salad', business_id=6)
    food51 = Food(name='Caesar Salad', business_id=6)
    food52 = Food(name='Pastrami Sandwich', business_id=6)
    food53 = Food(name='Cheesesteak', business_id=6)
    food54 = Food(name='Caesar Salad', business_id=6)
    food55 = Food(name='Build Your Own Sandwich', business_id=6)
    food56 = Food(name='Pulled Pork', business_id=6)
    food57 = Food(name='Breakfast Sandwich', business_id=6)
    food58 = Food(name='Bagel', business_id=7)
    food59 = Food(name='Muffin', business_id=7)
    food60 = Food(name='Croissant', business_id=7)
    food61 = Food(name='Yogurt', business_id=7)
    food62 = Food(name='"Nice" Cream', business_id=7)
    food63 = Food(name='Fruit Salad', business_id=7)
    food64 = Food(name='Garden Salad', business_id=7)
    food65 = Food(name='Caesar Salad', business_id=8)
    food66 = Food(name='Pastrami Sandwich', business_id=8)
    food67 = Food(name='Cheesesteak', business_id=8)
    food68 = Food(name='Caesar Salad', business_id=8)
    food69 = Food(name='Build Your Own Sandwich', business_id=8)
    food70 = Food(name='Pulled Pork', business_id=8)
    food71 = Food(name='Breakfast Sandwich', business_id=8)
    food72 = Food(name='Bagel', business_id=8)
    food73 = Food(name='Muffin', business_id=8)
    food74 = Food(name='Croissant', business_id=8)
    food75 = Food(name='Yogurt', business_id=8)
    food76 = Food(name='"Nice" Cream', business_id=8)
    food77 = Food(name='Fruit Salad', business_id=8)
    food78 = Food(name='Garden Salad', business_id=8)
    food79 = Food(name='Caesar Salad', business_id=9)
    food80 = Food(name='Pastrami Sandwich', business_id=9)
    food81 = Food(name='Cheesesteak', business_id=9)
    food82 = Food(name='Caesar Salad', business_id=9)
    food83 = Food(name='Build Your Own Sandwich', business_id=9)
    food84 = Food(name='Pulled Pork', business_id=9)
    food85 = Food(name='Breakfast Sandwich', business_id=9)
    food86 = Food(name='Bagel', business_id=10)
    food87 = Food(name='Muffin', business_id=10)
    food88 = Food(name='Croissant', business_id=10)
    food89 = Food(name='Yogurt', business_id=10)
    food90 = Food(name='"Nice" Cream', business_id=10)
    food91 = Food(name='Fruit Salad', business_id=10)
    food92 = Food(name='Garden Salad', business_id=10)
    food93 = Food(name='Caesar Salad', business_id=10)
    food94 = Food(name='Pastrami Sandwich', business_id=10)
    food95 = Food(name='Cheesesteak', business_id=10)
    food96 = Food(name='Caesar Salad', business_id=11)
    food97 = Food(name='Build Your Own Sandwich', business_id=11)
    food98 = Food(name='Pulled Pork', business_id=11)
    food99 = Food(name='Breakfast Sandwich', business_id=11)
    food100 = Food(name='Bagel', business_id=11)
    food101 = Food(name='Muffin', business_id=11)
    food102 = Food(name='Croissant', business_id=11)
    food103 = Food(name='Yogurt', business_id=12)
    food104 = Food(name='"Nice" Cream', business_id=12)
    food105 = Food(name='Fruit Salad', business_id=12)
    food106 = Food(name='Garden Salad', business_id=12)
    food107 = Food(name='Caesar Salad', business_id=12)
    food108 = Food(name='Pastrami Sandwich', business_id=12)
    food109 = Food(name='Cheesesteak', business_id=12)
    food110 = Food(name='Caesar Salad', business_id=12)
    food111 = Food(name='Build Your Own Sandwich', business_id=12)
    food112 = Food(name='Pulled Pork', business_id=12)

    food_list = [food1, food2, food3, food4, food5, food6, food7, food8, food9, food10, food11, food12, food13, food14, food15, food16, food17, food18, food19, food20, food21, food22, food23, food24, food25, food26, food27, food28, food29, food30, food31, food32, food33, food34, food35, food36, food37, food38, food39, food40, food41, food42, food43, food44, food45, food46, food47, food48, food49, food50, food51, food52, food53, food54, food55, food56, food57, food58, food59, food60, food61, food62, food63, food64, food65, food66, food67, food68, food69, food70, food71, food72, food73, food74, food75, food76, food77, food78, food79, food80, food81, food82, food83, food84, food85, food86, food87, food88, food89, food90, food91, food92, food93, food94, food95, food96, food97, food98, food99, food100, food101, food102, food103, food104, food105, food106, food107, food108, food109, food110, food111, food112]

    for food_item in food_list:
        db.session.add(food_item)
    db.session.commit()


def undo_food():
    db.session.execute('TRUNCATE food, reviews, categories, features, associations, biz_features, businesses, users RESTART identity;')
    db.session.commit()
