"""empty message

Revision ID: 5018d58f05ac
Revises: 6e084fbf0d50
Create Date: 2021-01-06 14:01:52.399863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5018d58f05ac'
down_revision = '6e084fbf0d50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('associations',
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], )
    )
    op.drop_table('features')
    op.add_column('businesses', sa.Column('delivery', sa.Boolean(), nullable=True))
    op.add_column('businesses', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('businesses', sa.Column('takeout', sa.Boolean(), nullable=True))
    op.drop_constraint('businesses_category_id_fkey', 'businesses', type_='foreignkey')
    op.drop_column('businesses', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('businesses_category_id_fkey', 'businesses', 'categories', ['category_id'], ['id'])
    op.drop_column('businesses', 'takeout')
    op.drop_column('businesses', 'description')
    op.drop_column('businesses', 'delivery')
    op.create_table('features',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('takeout', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('delivery', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name='features_business_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='features_pkey')
    )
    op.drop_table('associations')
    # ### end Alembic commands ###
