"""empty message

Revision ID: c8951e1ea339
Revises: d37214ad271a
Create Date: 2021-01-14 13:54:02.005714

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c8951e1ea339'
down_revision = 'd37214ad271a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('closing_hour', sa.Integer(), nullable=True))
    op.add_column('businesses', sa.Column('closing_min', sa.Integer(), nullable=True))
    op.add_column('businesses', sa.Column('opening_hour', sa.Integer(), nullable=True))
    op.add_column('businesses', sa.Column('opening_min', sa.Integer(), nullable=True))
    op.drop_column('businesses', 'opening')
    op.drop_column('businesses', 'closing')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('closing', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('businesses', sa.Column('opening', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('businesses', 'opening_min')
    op.drop_column('businesses', 'opening_hour')
    op.drop_column('businesses', 'closing_min')
    op.drop_column('businesses', 'closing_hour')
    # ### end Alembic commands ###
