"""empty message

Revision ID: d37214ad271a
Revises: 8abf4f3452c7
Create Date: 2021-01-14 13:11:00.472244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd37214ad271a'
down_revision = '8abf4f3452c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('closing', sa.DateTime(), nullable=True))
    op.add_column('businesses', sa.Column('opening', sa.DateTime(), nullable=True))
    op.drop_column('features', 'icon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('features', sa.Column('icon', sa.VARCHAR(length=25), autoincrement=False, nullable=True))
    op.drop_column('businesses', 'opening')
    op.drop_column('businesses', 'closing')
    # ### end Alembic commands ###
